default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  host: localhost
  port: 5432


development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

production:
  <<: *default
